pipelineJob('Deploy-K8s-Cluster') {
  definition {
    cps {
      script('''

      pipeline {
  agent any
  stages {
    stage('Stage 1') {
      steps {
        echo 'Hello world!'
      }
    }
  }
}

      '''.stripIndent())
      sandbox()
    }
  }
}